/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ElectricityPaymentStreamInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createStream"
      | "getStreamInfo"
      | "pricingHistory"
      | "pricingHistoryLength"
      | "reportUsageWithPricing"
      | "settle"
      | "stopStream"
      | "streamCount"
      | "streams"
      | "topUpDeposit"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositAdded"
      | "LowBalanceWarning"
      | "PricingUpdated"
      | "SettlementExecuted"
      | "SettlementFailed"
      | "SettlementScheduled"
      | "StreamCreated"
      | "StreamPaused"
      | "StreamResumed"
      | "UsageReported"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createStream",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getStreamInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pricingHistory",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pricingHistoryLength",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reportUsageWithPricing",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "settle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stopStream",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "streamCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "streams",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "topUpDeposit",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStreamInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pricingHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pricingHistoryLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportUsageWithPricing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stopStream", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "streamCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "streams", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "topUpDeposit",
    data: BytesLike
  ): Result;
}

export namespace DepositAddedEvent {
  export type InputTuple = [
    streamId: BigNumberish,
    sender: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [streamId: bigint, sender: string, amount: bigint];
  export interface OutputObject {
    streamId: bigint;
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LowBalanceWarningEvent {
  export type InputTuple = [
    streamId: BigNumberish,
    deposit: BigNumberish,
    accrued: BigNumberish,
    percentUsed: BigNumberish
  ];
  export type OutputTuple = [
    streamId: bigint,
    deposit: bigint,
    accrued: bigint,
    percentUsed: bigint
  ];
  export interface OutputObject {
    streamId: bigint;
    deposit: bigint;
    accrued: bigint;
    percentUsed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PricingUpdatedEvent {
  export type InputTuple = [
    streamId: BigNumberish,
    baseRate: BigNumberish,
    congestionFactor: BigNumberish,
    effectiveRate: BigNumberish
  ];
  export type OutputTuple = [
    streamId: bigint,
    baseRate: bigint,
    congestionFactor: bigint,
    effectiveRate: bigint
  ];
  export interface OutputObject {
    streamId: bigint;
    baseRate: bigint;
    congestionFactor: bigint;
    effectiveRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementExecutedEvent {
  export type InputTuple = [
    streamId: BigNumberish,
    timestamp: BigNumberish,
    count: BigNumberish,
    amountPaid: BigNumberish,
    remainingDeposit: BigNumberish,
    remainingAccrued: BigNumberish
  ];
  export type OutputTuple = [
    streamId: bigint,
    timestamp: bigint,
    count: bigint,
    amountPaid: bigint,
    remainingDeposit: bigint,
    remainingAccrued: bigint
  ];
  export interface OutputObject {
    streamId: bigint;
    timestamp: bigint;
    count: bigint;
    amountPaid: bigint;
    remainingDeposit: bigint;
    remainingAccrued: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementFailedEvent {
  export type InputTuple = [
    streamId: BigNumberish,
    reason: string,
    needed: BigNumberish,
    available: BigNumberish
  ];
  export type OutputTuple = [
    streamId: bigint,
    reason: string,
    needed: bigint,
    available: bigint
  ];
  export interface OutputObject {
    streamId: bigint;
    reason: string;
    needed: bigint;
    available: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementScheduledEvent {
  export type InputTuple = [
    streamId: BigNumberish,
    scheduledTime: BigNumberish,
    desiredTime: BigNumberish,
    scheduleAddress: AddressLike
  ];
  export type OutputTuple = [
    streamId: bigint,
    scheduledTime: bigint,
    desiredTime: bigint,
    scheduleAddress: string
  ];
  export interface OutputObject {
    streamId: bigint;
    scheduledTime: bigint;
    desiredTime: bigint;
    scheduleAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamCreatedEvent {
  export type InputTuple = [
    streamId: BigNumberish,
    payer: AddressLike,
    payee: AddressLike,
    intervalSecs: BigNumberish,
    baseRate: BigNumberish
  ];
  export type OutputTuple = [
    streamId: bigint,
    payer: string,
    payee: string,
    intervalSecs: bigint,
    baseRate: bigint
  ];
  export interface OutputObject {
    streamId: bigint;
    payer: string;
    payee: string;
    intervalSecs: bigint;
    baseRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamPausedEvent {
  export type InputTuple = [streamId: BigNumberish, reason: string];
  export type OutputTuple = [streamId: bigint, reason: string];
  export interface OutputObject {
    streamId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamResumedEvent {
  export type InputTuple = [streamId: BigNumberish];
  export type OutputTuple = [streamId: bigint];
  export interface OutputObject {
    streamId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsageReportedEvent {
  export type InputTuple = [
    streamId: BigNumberish,
    deltaUsage: BigNumberish,
    effectiveRate: BigNumberish,
    cost: BigNumberish,
    totalAccrued: BigNumberish
  ];
  export type OutputTuple = [
    streamId: bigint,
    deltaUsage: bigint,
    effectiveRate: bigint,
    cost: bigint,
    totalAccrued: bigint
  ];
  export interface OutputObject {
    streamId: bigint;
    deltaUsage: bigint;
    effectiveRate: bigint;
    cost: bigint;
    totalAccrued: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ElectricityPaymentStream extends BaseContract {
  connect(runner?: ContractRunner | null): ElectricityPaymentStream;
  waitForDeployment(): Promise<this>;

  interface: ElectricityPaymentStreamInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createStream: TypedContractMethod<
    [
      payee: AddressLike,
      baseRatePerUnit: BigNumberish,
      maxPayPerInterval: BigNumberish,
      intervalSecs: BigNumberish,
      oracle: AddressLike,
      schedulePayer_: AddressLike,
      usePayerScheduling_: boolean
    ],
    [bigint],
    "payable"
  >;

  getStreamInfo: TypedContractMethod<
    [streamId: BigNumberish],
    [
      [
        string,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        payer: string;
        payee: string;
        active: boolean;
        depositBalance: bigint;
        accruedAmount: bigint;
        totalUsageUnits: bigint;
        lastSettlementTime: bigint;
        nextSettlementTime: bigint;
        settlementCount: bigint;
      }
    ],
    "view"
  >;

  pricingHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        baseRate: bigint;
        congestionFactor: bigint;
        effectiveRate: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  pricingHistoryLength: TypedContractMethod<
    [streamId: BigNumberish],
    [bigint],
    "view"
  >;

  reportUsageWithPricing: TypedContractMethod<
    [
      streamId: BigNumberish,
      newTotalUsage: BigNumberish,
      timestamp_: BigNumberish,
      nonce: BigNumberish,
      baseRate: BigNumberish,
      congestionFactor: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  settle: TypedContractMethod<[streamId: BigNumberish], [void], "nonpayable">;

  stopStream: TypedContractMethod<
    [streamId: BigNumberish],
    [void],
    "nonpayable"
  >;

  streamCount: TypedContractMethod<[], [bigint], "view">;

  streams: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        string,
        bigint,
        string,
        boolean,
        bigint
      ] & {
        streamId: bigint;
        payer: string;
        payee: string;
        baseRatePerUnit: bigint;
        maxPayPerInterval: bigint;
        settlementIntervalSecs: bigint;
        authorizedOracle: string;
        depositBalance: bigint;
        accruedAmount: bigint;
        totalUsageUnits: bigint;
        active: boolean;
        lastSettlementTime: bigint;
        settlementCount: bigint;
        lastScheduleAddress: string;
        nextSettlementTime: bigint;
        schedulePayer: string;
        usePayerScheduling: boolean;
        oracleNonce: bigint;
      }
    ],
    "view"
  >;

  topUpDeposit: TypedContractMethod<
    [streamId: BigNumberish],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createStream"
  ): TypedContractMethod<
    [
      payee: AddressLike,
      baseRatePerUnit: BigNumberish,
      maxPayPerInterval: BigNumberish,
      intervalSecs: BigNumberish,
      oracle: AddressLike,
      schedulePayer_: AddressLike,
      usePayerScheduling_: boolean
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getStreamInfo"
  ): TypedContractMethod<
    [streamId: BigNumberish],
    [
      [
        string,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        payer: string;
        payee: string;
        active: boolean;
        depositBalance: bigint;
        accruedAmount: bigint;
        totalUsageUnits: bigint;
        lastSettlementTime: bigint;
        nextSettlementTime: bigint;
        settlementCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pricingHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        baseRate: bigint;
        congestionFactor: bigint;
        effectiveRate: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pricingHistoryLength"
  ): TypedContractMethod<[streamId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "reportUsageWithPricing"
  ): TypedContractMethod<
    [
      streamId: BigNumberish,
      newTotalUsage: BigNumberish,
      timestamp_: BigNumberish,
      nonce: BigNumberish,
      baseRate: BigNumberish,
      congestionFactor: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settle"
  ): TypedContractMethod<[streamId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stopStream"
  ): TypedContractMethod<[streamId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "streamCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "streams"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        string,
        bigint,
        string,
        boolean,
        bigint
      ] & {
        streamId: bigint;
        payer: string;
        payee: string;
        baseRatePerUnit: bigint;
        maxPayPerInterval: bigint;
        settlementIntervalSecs: bigint;
        authorizedOracle: string;
        depositBalance: bigint;
        accruedAmount: bigint;
        totalUsageUnits: bigint;
        active: boolean;
        lastSettlementTime: bigint;
        settlementCount: bigint;
        lastScheduleAddress: string;
        nextSettlementTime: bigint;
        schedulePayer: string;
        usePayerScheduling: boolean;
        oracleNonce: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "topUpDeposit"
  ): TypedContractMethod<[streamId: BigNumberish], [void], "payable">;

  getEvent(
    key: "DepositAdded"
  ): TypedContractEvent<
    DepositAddedEvent.InputTuple,
    DepositAddedEvent.OutputTuple,
    DepositAddedEvent.OutputObject
  >;
  getEvent(
    key: "LowBalanceWarning"
  ): TypedContractEvent<
    LowBalanceWarningEvent.InputTuple,
    LowBalanceWarningEvent.OutputTuple,
    LowBalanceWarningEvent.OutputObject
  >;
  getEvent(
    key: "PricingUpdated"
  ): TypedContractEvent<
    PricingUpdatedEvent.InputTuple,
    PricingUpdatedEvent.OutputTuple,
    PricingUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SettlementExecuted"
  ): TypedContractEvent<
    SettlementExecutedEvent.InputTuple,
    SettlementExecutedEvent.OutputTuple,
    SettlementExecutedEvent.OutputObject
  >;
  getEvent(
    key: "SettlementFailed"
  ): TypedContractEvent<
    SettlementFailedEvent.InputTuple,
    SettlementFailedEvent.OutputTuple,
    SettlementFailedEvent.OutputObject
  >;
  getEvent(
    key: "SettlementScheduled"
  ): TypedContractEvent<
    SettlementScheduledEvent.InputTuple,
    SettlementScheduledEvent.OutputTuple,
    SettlementScheduledEvent.OutputObject
  >;
  getEvent(
    key: "StreamCreated"
  ): TypedContractEvent<
    StreamCreatedEvent.InputTuple,
    StreamCreatedEvent.OutputTuple,
    StreamCreatedEvent.OutputObject
  >;
  getEvent(
    key: "StreamPaused"
  ): TypedContractEvent<
    StreamPausedEvent.InputTuple,
    StreamPausedEvent.OutputTuple,
    StreamPausedEvent.OutputObject
  >;
  getEvent(
    key: "StreamResumed"
  ): TypedContractEvent<
    StreamResumedEvent.InputTuple,
    StreamResumedEvent.OutputTuple,
    StreamResumedEvent.OutputObject
  >;
  getEvent(
    key: "UsageReported"
  ): TypedContractEvent<
    UsageReportedEvent.InputTuple,
    UsageReportedEvent.OutputTuple,
    UsageReportedEvent.OutputObject
  >;

  filters: {
    "DepositAdded(uint256,address,uint256)": TypedContractEvent<
      DepositAddedEvent.InputTuple,
      DepositAddedEvent.OutputTuple,
      DepositAddedEvent.OutputObject
    >;
    DepositAdded: TypedContractEvent<
      DepositAddedEvent.InputTuple,
      DepositAddedEvent.OutputTuple,
      DepositAddedEvent.OutputObject
    >;

    "LowBalanceWarning(uint256,uint256,uint256,uint256)": TypedContractEvent<
      LowBalanceWarningEvent.InputTuple,
      LowBalanceWarningEvent.OutputTuple,
      LowBalanceWarningEvent.OutputObject
    >;
    LowBalanceWarning: TypedContractEvent<
      LowBalanceWarningEvent.InputTuple,
      LowBalanceWarningEvent.OutputTuple,
      LowBalanceWarningEvent.OutputObject
    >;

    "PricingUpdated(uint256,uint256,uint256,uint256)": TypedContractEvent<
      PricingUpdatedEvent.InputTuple,
      PricingUpdatedEvent.OutputTuple,
      PricingUpdatedEvent.OutputObject
    >;
    PricingUpdated: TypedContractEvent<
      PricingUpdatedEvent.InputTuple,
      PricingUpdatedEvent.OutputTuple,
      PricingUpdatedEvent.OutputObject
    >;

    "SettlementExecuted(uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      SettlementExecutedEvent.InputTuple,
      SettlementExecutedEvent.OutputTuple,
      SettlementExecutedEvent.OutputObject
    >;
    SettlementExecuted: TypedContractEvent<
      SettlementExecutedEvent.InputTuple,
      SettlementExecutedEvent.OutputTuple,
      SettlementExecutedEvent.OutputObject
    >;

    "SettlementFailed(uint256,string,uint256,uint256)": TypedContractEvent<
      SettlementFailedEvent.InputTuple,
      SettlementFailedEvent.OutputTuple,
      SettlementFailedEvent.OutputObject
    >;
    SettlementFailed: TypedContractEvent<
      SettlementFailedEvent.InputTuple,
      SettlementFailedEvent.OutputTuple,
      SettlementFailedEvent.OutputObject
    >;

    "SettlementScheduled(uint256,uint256,uint256,address)": TypedContractEvent<
      SettlementScheduledEvent.InputTuple,
      SettlementScheduledEvent.OutputTuple,
      SettlementScheduledEvent.OutputObject
    >;
    SettlementScheduled: TypedContractEvent<
      SettlementScheduledEvent.InputTuple,
      SettlementScheduledEvent.OutputTuple,
      SettlementScheduledEvent.OutputObject
    >;

    "StreamCreated(uint256,address,address,uint256,uint256)": TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;
    StreamCreated: TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;

    "StreamPaused(uint256,string)": TypedContractEvent<
      StreamPausedEvent.InputTuple,
      StreamPausedEvent.OutputTuple,
      StreamPausedEvent.OutputObject
    >;
    StreamPaused: TypedContractEvent<
      StreamPausedEvent.InputTuple,
      StreamPausedEvent.OutputTuple,
      StreamPausedEvent.OutputObject
    >;

    "StreamResumed(uint256)": TypedContractEvent<
      StreamResumedEvent.InputTuple,
      StreamResumedEvent.OutputTuple,
      StreamResumedEvent.OutputObject
    >;
    StreamResumed: TypedContractEvent<
      StreamResumedEvent.InputTuple,
      StreamResumedEvent.OutputTuple,
      StreamResumedEvent.OutputObject
    >;

    "UsageReported(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      UsageReportedEvent.InputTuple,
      UsageReportedEvent.OutputTuple,
      UsageReportedEvent.OutputObject
    >;
    UsageReported: TypedContractEvent<
      UsageReportedEvent.InputTuple,
      UsageReportedEvent.OutputTuple,
      UsageReportedEvent.OutputObject
    >;
  };
}
