/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace UtilityReceivable {
  export type ReceivableStruct = {
    tokenId: BigNumberish;
    utilityProvider: AddressLike;
    customer: AddressLike;
    amountUSD: BigNumberish;
    amountADI: BigNumberish;
    dueDate: BigNumberish;
    status: BigNumberish;
    hederaTxHash: BytesLike;
    mintedAt: BigNumberish;
  };

  export type ReceivableStructOutput = [
    tokenId: bigint,
    utilityProvider: string,
    customer: string,
    amountUSD: bigint,
    amountADI: bigint,
    dueDate: bigint,
    status: bigint,
    hederaTxHash: string,
    mintedAt: bigint
  ] & {
    tokenId: bigint;
    utilityProvider: string;
    customer: string;
    amountUSD: bigint;
    amountADI: bigint;
    dueDate: bigint;
    status: bigint;
    hederaTxHash: string;
    mintedAt: bigint;
  };
}

export interface UtilityReceivableInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADI_DECIMALS"
      | "ADI_PRICE_USD"
      | "USD_DECIMALS"
      | "balanceOf"
      | "convertADIToUSD"
      | "convertUSDToADI"
      | "getOutstandingBalance"
      | "getReceivable"
      | "getTotalPaid"
      | "markAsDefaulted"
      | "markAsPaid"
      | "mintReceivable"
      | "owner"
      | "ownerOf"
      | "payReceivable"
      | "processedHederaTx"
      | "receivables"
      | "relayer"
      | "setRelayer"
      | "totalOutstanding"
      | "totalPaid"
      | "totalReceivables"
      | "transfer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ReceivableMinted"
      | "ReceivablePaid"
      | "ReceivableTransferred"
      | "RelayerUpdated"
      | "StatusUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADI_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ADI_PRICE_USD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USD_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "convertADIToUSD",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertUSDToADI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutstandingBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReceivable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPaid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markAsDefaulted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markAsPaid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintReceivable",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "payReceivable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processedHederaTx",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receivables",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalOutstanding",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "totalPaid", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalReceivables",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ADI_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ADI_PRICE_USD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USD_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convertADIToUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertUSDToADI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutstandingBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReceivable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markAsDefaulted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markAsPaid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintReceivable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payReceivable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processedHederaTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receivables",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalOutstanding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalPaid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalReceivables",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
}

export namespace ReceivableMintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    utilityProvider: AddressLike,
    customer: AddressLike,
    amountUSD: BigNumberish,
    amountADI: BigNumberish,
    status: BigNumberish,
    hederaTxHash: BytesLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    utilityProvider: string,
    customer: string,
    amountUSD: bigint,
    amountADI: bigint,
    status: bigint,
    hederaTxHash: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    utilityProvider: string;
    customer: string;
    amountUSD: bigint;
    amountADI: bigint;
    status: bigint;
    hederaTxHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceivablePaidEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    payer: AddressLike,
    amountADI: BigNumberish
  ];
  export type OutputTuple = [tokenId: bigint, payer: string, amountADI: bigint];
  export interface OutputObject {
    tokenId: bigint;
    payer: string;
    amountADI: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceivableTransferredEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [tokenId: bigint, from: string, to: string];
  export interface OutputObject {
    tokenId: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerUpdatedEvent {
  export type InputTuple = [oldRelayer: AddressLike, newRelayer: AddressLike];
  export type OutputTuple = [oldRelayer: string, newRelayer: string];
  export interface OutputObject {
    oldRelayer: string;
    newRelayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UtilityReceivable extends BaseContract {
  connect(runner?: ContractRunner | null): UtilityReceivable;
  waitForDeployment(): Promise<this>;

  interface: UtilityReceivableInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADI_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  ADI_PRICE_USD: TypedContractMethod<[], [bigint], "view">;

  USD_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  convertADIToUSD: TypedContractMethod<
    [amountADI: BigNumberish],
    [bigint],
    "view"
  >;

  convertUSDToADI: TypedContractMethod<
    [amountUSD: BigNumberish],
    [bigint],
    "view"
  >;

  getOutstandingBalance: TypedContractMethod<[], [bigint], "view">;

  getReceivable: TypedContractMethod<
    [tokenId: BigNumberish],
    [UtilityReceivable.ReceivableStructOutput],
    "view"
  >;

  getTotalPaid: TypedContractMethod<[], [bigint], "view">;

  markAsDefaulted: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  markAsPaid: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  mintReceivable: TypedContractMethod<
    [
      utilityProvider: AddressLike,
      customer: AddressLike,
      amountUSD: BigNumberish,
      dueDate: BigNumberish,
      status: BigNumberish,
      hederaTxHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  payReceivable: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "payable"
  >;

  processedHederaTx: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  receivables: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        tokenId: bigint;
        utilityProvider: string;
        customer: string;
        amountUSD: bigint;
        amountADI: bigint;
        dueDate: bigint;
        status: bigint;
        hederaTxHash: string;
        mintedAt: bigint;
      }
    ],
    "view"
  >;

  relayer: TypedContractMethod<[], [string], "view">;

  setRelayer: TypedContractMethod<
    [_relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  totalOutstanding: TypedContractMethod<[], [bigint], "view">;

  totalPaid: TypedContractMethod<[], [bigint], "view">;

  totalReceivables: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADI_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ADI_PRICE_USD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USD_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertADIToUSD"
  ): TypedContractMethod<[amountADI: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertUSDToADI"
  ): TypedContractMethod<[amountUSD: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOutstandingBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReceivable"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [UtilityReceivable.ReceivableStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalPaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markAsDefaulted"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "markAsPaid"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mintReceivable"
  ): TypedContractMethod<
    [
      utilityProvider: AddressLike,
      customer: AddressLike,
      amountUSD: BigNumberish,
      dueDate: BigNumberish,
      status: BigNumberish,
      hederaTxHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "payReceivable"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "processedHederaTx"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "receivables"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        tokenId: bigint;
        utilityProvider: string;
        customer: string;
        amountUSD: bigint;
        amountADI: bigint;
        dueDate: bigint;
        status: bigint;
        hederaTxHash: string;
        mintedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setRelayer"
  ): TypedContractMethod<[_relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalOutstanding"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReceivables"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ReceivableMinted"
  ): TypedContractEvent<
    ReceivableMintedEvent.InputTuple,
    ReceivableMintedEvent.OutputTuple,
    ReceivableMintedEvent.OutputObject
  >;
  getEvent(
    key: "ReceivablePaid"
  ): TypedContractEvent<
    ReceivablePaidEvent.InputTuple,
    ReceivablePaidEvent.OutputTuple,
    ReceivablePaidEvent.OutputObject
  >;
  getEvent(
    key: "ReceivableTransferred"
  ): TypedContractEvent<
    ReceivableTransferredEvent.InputTuple,
    ReceivableTransferredEvent.OutputTuple,
    ReceivableTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RelayerUpdated"
  ): TypedContractEvent<
    RelayerUpdatedEvent.InputTuple,
    RelayerUpdatedEvent.OutputTuple,
    RelayerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StatusUpdated"
  ): TypedContractEvent<
    StatusUpdatedEvent.InputTuple,
    StatusUpdatedEvent.OutputTuple,
    StatusUpdatedEvent.OutputObject
  >;

  filters: {
    "ReceivableMinted(uint256,address,address,uint256,uint256,uint8,bytes32)": TypedContractEvent<
      ReceivableMintedEvent.InputTuple,
      ReceivableMintedEvent.OutputTuple,
      ReceivableMintedEvent.OutputObject
    >;
    ReceivableMinted: TypedContractEvent<
      ReceivableMintedEvent.InputTuple,
      ReceivableMintedEvent.OutputTuple,
      ReceivableMintedEvent.OutputObject
    >;

    "ReceivablePaid(uint256,address,uint256)": TypedContractEvent<
      ReceivablePaidEvent.InputTuple,
      ReceivablePaidEvent.OutputTuple,
      ReceivablePaidEvent.OutputObject
    >;
    ReceivablePaid: TypedContractEvent<
      ReceivablePaidEvent.InputTuple,
      ReceivablePaidEvent.OutputTuple,
      ReceivablePaidEvent.OutputObject
    >;

    "ReceivableTransferred(uint256,address,address)": TypedContractEvent<
      ReceivableTransferredEvent.InputTuple,
      ReceivableTransferredEvent.OutputTuple,
      ReceivableTransferredEvent.OutputObject
    >;
    ReceivableTransferred: TypedContractEvent<
      ReceivableTransferredEvent.InputTuple,
      ReceivableTransferredEvent.OutputTuple,
      ReceivableTransferredEvent.OutputObject
    >;

    "RelayerUpdated(address,address)": TypedContractEvent<
      RelayerUpdatedEvent.InputTuple,
      RelayerUpdatedEvent.OutputTuple,
      RelayerUpdatedEvent.OutputObject
    >;
    RelayerUpdated: TypedContractEvent<
      RelayerUpdatedEvent.InputTuple,
      RelayerUpdatedEvent.OutputTuple,
      RelayerUpdatedEvent.OutputObject
    >;

    "StatusUpdated(uint256,uint8,uint8)": TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;
    StatusUpdated: TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;
  };
}
