/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { MockPRNG, MockPRNGInterface } from "../../contracts/MockPRNG";

const _abi = [
  {
    inputs: [],
    name: "callCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPseudorandomSeed",
    outputs: [
      {
        internalType: "bytes32",
        name: "seed",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461001657610110908161001c8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c9081634b28f9a21460be575063d83bf9a114603457600080fd5b3460bb578060031936011260bb578054600019811460a757600101808255604051906020820190428252436040840152606083015260608252608082019180831067ffffffffffffffff84111760935760209350826040525190208152f35b634e487b7160e01b84526041600452602484fd5b634e487b7160e01b82526011600452602482fd5b80fd5b90503460d6578160031936011260d657602091548152f35b5080fdfea26469706673582212201a536898928ef540a6feb86bc0b577637738f2e2de66dbf9949f77cba1dbffba64736f6c63430008180033";

type MockPRNGConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockPRNGConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockPRNG__factory extends ContractFactory {
  constructor(...args: MockPRNGConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockPRNG & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockPRNG__factory {
    return super.connect(runner) as MockPRNG__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockPRNGInterface {
    return new Interface(_abi) as MockPRNGInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockPRNG {
    return new Contract(address, _abi, runner) as unknown as MockPRNG;
  }
}
