/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ElectricityPaymentStream",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ElectricityPaymentStream__factory>;
    getContractFactory(
      name: "HourlyUsageScheduler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HourlyUsageScheduler__factory>;
    getContractFactory(
      name: "MockElectricityOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockElectricityOracle__factory>;
    getContractFactory(
      name: "MockHSSPrecompile",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockHSSPrecompile__factory>;
    getContractFactory(
      name: "MockPRNG",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockPRNG__factory>;

    getContractAt(
      name: "ElectricityPaymentStream",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ElectricityPaymentStream>;
    getContractAt(
      name: "HourlyUsageScheduler",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HourlyUsageScheduler>;
    getContractAt(
      name: "MockElectricityOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockElectricityOracle>;
    getContractAt(
      name: "MockHSSPrecompile",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockHSSPrecompile>;
    getContractAt(
      name: "MockPRNG",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockPRNG>;

    deployContract(
      name: "ElectricityPaymentStream",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ElectricityPaymentStream>;
    deployContract(
      name: "HourlyUsageScheduler",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HourlyUsageScheduler>;
    deployContract(
      name: "MockElectricityOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockElectricityOracle>;
    deployContract(
      name: "MockHSSPrecompile",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockHSSPrecompile>;
    deployContract(
      name: "MockPRNG",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockPRNG>;

    deployContract(
      name: "ElectricityPaymentStream",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ElectricityPaymentStream>;
    deployContract(
      name: "HourlyUsageScheduler",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HourlyUsageScheduler>;
    deployContract(
      name: "MockElectricityOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockElectricityOracle>;
    deployContract(
      name: "MockHSSPrecompile",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockHSSPrecompile>;
    deployContract(
      name: "MockPRNG",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockPRNG>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
