/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface HourlyUsageSchedulerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeSchedule"
      | "bootstrapSchedule"
      | "fetchAndStoreUsage"
      | "getLatestKWh"
      | "lastFetchTimestamp"
      | "lastFetchedHourlyKWh"
      | "lastFetchedRoundId"
      | "oracle"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "HourlyUpdateScheduled" | "UsageFetched"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeSchedule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bootstrapSchedule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fetchAndStoreUsage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestKWh",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastFetchTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastFetchedHourlyKWh",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastFetchedRoundId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "activeSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bootstrapSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchAndStoreUsage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestKWh",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastFetchTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastFetchedHourlyKWh",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastFetchedRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
}

export namespace HourlyUpdateScheduledEvent {
  export type InputTuple = [
    scheduleAddress: AddressLike,
    executeAt: BigNumberish
  ];
  export type OutputTuple = [scheduleAddress: string, executeAt: bigint];
  export interface OutputObject {
    scheduleAddress: string;
    executeAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsageFetchedEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    hourlyKWh: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    roundId: bigint,
    hourlyKWh: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    roundId: bigint;
    hourlyKWh: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HourlyUsageScheduler extends BaseContract {
  connect(runner?: ContractRunner | null): HourlyUsageScheduler;
  waitForDeployment(): Promise<this>;

  interface: HourlyUsageSchedulerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeSchedule: TypedContractMethod<[], [string], "view">;

  bootstrapSchedule: TypedContractMethod<[], [void], "nonpayable">;

  fetchAndStoreUsage: TypedContractMethod<[], [void], "nonpayable">;

  getLatestKWh: TypedContractMethod<
    [],
    [[bigint, bigint] & { kWh: bigint; timestamp: bigint }],
    "view"
  >;

  lastFetchTimestamp: TypedContractMethod<[], [bigint], "view">;

  lastFetchedHourlyKWh: TypedContractMethod<[], [bigint], "view">;

  lastFetchedRoundId: TypedContractMethod<[], [bigint], "view">;

  oracle: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeSchedule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bootstrapSchedule"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fetchAndStoreUsage"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getLatestKWh"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { kWh: bigint; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastFetchTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastFetchedHourlyKWh"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastFetchedRoundId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "HourlyUpdateScheduled"
  ): TypedContractEvent<
    HourlyUpdateScheduledEvent.InputTuple,
    HourlyUpdateScheduledEvent.OutputTuple,
    HourlyUpdateScheduledEvent.OutputObject
  >;
  getEvent(
    key: "UsageFetched"
  ): TypedContractEvent<
    UsageFetchedEvent.InputTuple,
    UsageFetchedEvent.OutputTuple,
    UsageFetchedEvent.OutputObject
  >;

  filters: {
    "HourlyUpdateScheduled(address,uint256)": TypedContractEvent<
      HourlyUpdateScheduledEvent.InputTuple,
      HourlyUpdateScheduledEvent.OutputTuple,
      HourlyUpdateScheduledEvent.OutputObject
    >;
    HourlyUpdateScheduled: TypedContractEvent<
      HourlyUpdateScheduledEvent.InputTuple,
      HourlyUpdateScheduledEvent.OutputTuple,
      HourlyUpdateScheduledEvent.OutputObject
    >;

    "UsageFetched(uint80,uint256,uint256)": TypedContractEvent<
      UsageFetchedEvent.InputTuple,
      UsageFetchedEvent.OutputTuple,
      UsageFetchedEvent.OutputObject
    >;
    UsageFetched: TypedContractEvent<
      UsageFetchedEvent.InputTuple,
      UsageFetchedEvent.OutputTuple,
      UsageFetchedEvent.OutputObject
    >;
  };
}
