/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MockHSSPrecompileInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deleteCount"
      | "deleteSchedule"
      | "hasScheduleCapacity"
      | "lastCallData"
      | "lastDeletedSchedule"
      | "lastExpirySecond"
      | "lastGasLimit"
      | "lastScheduledTo"
      | "lastValue"
      | "scheduleCall"
      | "scheduleCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MockScheduleCreated" | "MockScheduleDeleted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deleteCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deleteSchedule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasScheduleCapacity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastCallData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastDeletedSchedule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastExpirySecond",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastGasLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastScheduledTo",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lastValue", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "scheduleCall",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleCount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "deleteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasScheduleCapacity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastCallData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDeletedSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastExpirySecond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastScheduledTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastValue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "scheduleCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleCount",
    data: BytesLike
  ): Result;
}

export namespace MockScheduleCreatedEvent {
  export type InputTuple = [
    to: AddressLike,
    expirySecond: BigNumberish,
    scheduleAddress: AddressLike
  ];
  export type OutputTuple = [
    to: string,
    expirySecond: bigint,
    scheduleAddress: string
  ];
  export interface OutputObject {
    to: string;
    expirySecond: bigint;
    scheduleAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MockScheduleDeletedEvent {
  export type InputTuple = [scheduleAddress: AddressLike];
  export type OutputTuple = [scheduleAddress: string];
  export interface OutputObject {
    scheduleAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockHSSPrecompile extends BaseContract {
  connect(runner?: ContractRunner | null): MockHSSPrecompile;
  waitForDeployment(): Promise<this>;

  interface: MockHSSPrecompileInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deleteCount: TypedContractMethod<[], [bigint], "view">;

  deleteSchedule: TypedContractMethod<
    [scheduleAddress: AddressLike],
    [bigint],
    "nonpayable"
  >;

  hasScheduleCapacity: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  lastCallData: TypedContractMethod<[], [string], "view">;

  lastDeletedSchedule: TypedContractMethod<[], [string], "view">;

  lastExpirySecond: TypedContractMethod<[], [bigint], "view">;

  lastGasLimit: TypedContractMethod<[], [bigint], "view">;

  lastScheduledTo: TypedContractMethod<[], [string], "view">;

  lastValue: TypedContractMethod<[], [bigint], "view">;

  scheduleCall: TypedContractMethod<
    [
      to: AddressLike,
      expirySecond: BigNumberish,
      gasLimit: BigNumberish,
      value: BigNumberish,
      callData: BytesLike
    ],
    [[bigint, string] & { responseCode: bigint; scheduleAddress: string }],
    "nonpayable"
  >;

  scheduleCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deleteCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deleteSchedule"
  ): TypedContractMethod<
    [scheduleAddress: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasScheduleCapacity"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastCallData"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastDeletedSchedule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastExpirySecond"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastGasLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastScheduledTo"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "scheduleCall"
  ): TypedContractMethod<
    [
      to: AddressLike,
      expirySecond: BigNumberish,
      gasLimit: BigNumberish,
      value: BigNumberish,
      callData: BytesLike
    ],
    [[bigint, string] & { responseCode: bigint; scheduleAddress: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scheduleCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "MockScheduleCreated"
  ): TypedContractEvent<
    MockScheduleCreatedEvent.InputTuple,
    MockScheduleCreatedEvent.OutputTuple,
    MockScheduleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MockScheduleDeleted"
  ): TypedContractEvent<
    MockScheduleDeletedEvent.InputTuple,
    MockScheduleDeletedEvent.OutputTuple,
    MockScheduleDeletedEvent.OutputObject
  >;

  filters: {
    "MockScheduleCreated(address,uint256,address)": TypedContractEvent<
      MockScheduleCreatedEvent.InputTuple,
      MockScheduleCreatedEvent.OutputTuple,
      MockScheduleCreatedEvent.OutputObject
    >;
    MockScheduleCreated: TypedContractEvent<
      MockScheduleCreatedEvent.InputTuple,
      MockScheduleCreatedEvent.OutputTuple,
      MockScheduleCreatedEvent.OutputObject
    >;

    "MockScheduleDeleted(address)": TypedContractEvent<
      MockScheduleDeletedEvent.InputTuple,
      MockScheduleDeletedEvent.OutputTuple,
      MockScheduleDeletedEvent.OutputObject
    >;
    MockScheduleDeleted: TypedContractEvent<
      MockScheduleDeletedEvent.InputTuple,
      MockScheduleDeletedEvent.OutputTuple,
      MockScheduleDeletedEvent.OutputObject
    >;
  };
}
