/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace MockElectricityOracle {
  export type MeterReadingStruct = {
    roundId: BigNumberish;
    cumulativeKWh: BigNumberish;
    hourlyKWh: BigNumberish;
    timestamp: BigNumberish;
    hour: BigNumberish;
    period: BigNumberish;
  };

  export type MeterReadingStructOutput = [
    roundId: bigint,
    cumulativeKWh: bigint,
    hourlyKWh: bigint,
    timestamp: bigint,
    hour: bigint,
    period: bigint
  ] & {
    roundId: bigint;
    cumulativeKWh: bigint;
    hourlyKWh: bigint;
    timestamp: bigint;
    hour: bigint;
    period: bigint;
  };
}

export interface MockElectricityOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "decimals"
      | "description"
      | "getRoundData"
      | "latestReading"
      | "latestRoundData"
      | "latestRoundId"
      | "oracleOperator"
      | "readings"
      | "transferOperator"
      | "updateReading"
      | "usageBetween"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MeterReadingUpdated" | "OperatorTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "description",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoundData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "latestReading",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "latestRoundData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "latestRoundId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oracleOperator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "readings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReading",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "usageBetween",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "description",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoundData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestReading",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestRoundData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "readings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReading",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usageBetween",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace MeterReadingUpdatedEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    cumulativeKWh: BigNumberish,
    hourlyKWh: BigNumberish,
    hour: BigNumberish,
    period: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    roundId: bigint,
    cumulativeKWh: bigint,
    hourlyKWh: bigint,
    hour: bigint,
    period: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    roundId: bigint;
    cumulativeKWh: bigint;
    hourlyKWh: bigint;
    hour: bigint;
    period: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorTransferredEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockElectricityOracle extends BaseContract {
  connect(runner?: ContractRunner | null): MockElectricityOracle;
  waitForDeployment(): Promise<this>;

  interface: MockElectricityOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  decimals: TypedContractMethod<[], [bigint], "view">;

  description: TypedContractMethod<[], [string], "view">;

  getRoundData: TypedContractMethod<
    [_roundId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        roundId: bigint;
        answer: bigint;
        startedAt: bigint;
        updatedAt: bigint;
        answeredInRound: bigint;
      }
    ],
    "view"
  >;

  latestReading: TypedContractMethod<
    [],
    [MockElectricityOracle.MeterReadingStructOutput],
    "view"
  >;

  latestRoundData: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        roundId: bigint;
        answer: bigint;
        startedAt: bigint;
        updatedAt: bigint;
        answeredInRound: bigint;
      }
    ],
    "view"
  >;

  latestRoundId: TypedContractMethod<[], [bigint], "view">;

  oracleOperator: TypedContractMethod<[], [string], "view">;

  readings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        roundId: bigint;
        cumulativeKWh: bigint;
        hourlyKWh: bigint;
        timestamp: bigint;
        hour: bigint;
        period: bigint;
      }
    ],
    "view"
  >;

  transferOperator: TypedContractMethod<
    [newOperator: AddressLike],
    [void],
    "nonpayable"
  >;

  updateReading: TypedContractMethod<
    [cumulativeKWh: BigNumberish, hourlyKWh: BigNumberish],
    [void],
    "nonpayable"
  >;

  usageBetween: TypedContractMethod<
    [fromRound: BigNumberish, toRound: BigNumberish],
    [bigint],
    "view"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "description"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRoundData"
  ): TypedContractMethod<
    [_roundId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        roundId: bigint;
        answer: bigint;
        startedAt: bigint;
        updatedAt: bigint;
        answeredInRound: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "latestReading"
  ): TypedContractMethod<
    [],
    [MockElectricityOracle.MeterReadingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "latestRoundData"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        roundId: bigint;
        answer: bigint;
        startedAt: bigint;
        updatedAt: bigint;
        answeredInRound: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "latestRoundId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracleOperator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "readings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        roundId: bigint;
        cumulativeKWh: bigint;
        hourlyKWh: bigint;
        timestamp: bigint;
        hour: bigint;
        period: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOperator"
  ): TypedContractMethod<[newOperator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateReading"
  ): TypedContractMethod<
    [cumulativeKWh: BigNumberish, hourlyKWh: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usageBetween"
  ): TypedContractMethod<
    [fromRound: BigNumberish, toRound: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "MeterReadingUpdated"
  ): TypedContractEvent<
    MeterReadingUpdatedEvent.InputTuple,
    MeterReadingUpdatedEvent.OutputTuple,
    MeterReadingUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorTransferred"
  ): TypedContractEvent<
    OperatorTransferredEvent.InputTuple,
    OperatorTransferredEvent.OutputTuple,
    OperatorTransferredEvent.OutputObject
  >;

  filters: {
    "MeterReadingUpdated(uint80,uint256,uint256,uint8,uint8,uint256)": TypedContractEvent<
      MeterReadingUpdatedEvent.InputTuple,
      MeterReadingUpdatedEvent.OutputTuple,
      MeterReadingUpdatedEvent.OutputObject
    >;
    MeterReadingUpdated: TypedContractEvent<
      MeterReadingUpdatedEvent.InputTuple,
      MeterReadingUpdatedEvent.OutputTuple,
      MeterReadingUpdatedEvent.OutputObject
    >;

    "OperatorTransferred(address,address)": TypedContractEvent<
      OperatorTransferredEvent.InputTuple,
      OperatorTransferredEvent.OutputTuple,
      OperatorTransferredEvent.OutputObject
    >;
    OperatorTransferred: TypedContractEvent<
      OperatorTransferredEvent.InputTuple,
      OperatorTransferredEvent.OutputTuple,
      OperatorTransferredEvent.OutputObject
    >;
  };
}
